export const metadata = {
  title: "Terms of Use — TapSnap",
  description: "The terms for using TapSnap, and important limits on part-matching.",
};

export default function Terms() {
  return (
    <main className="container" style={{ maxWidth: 760, padding: "32px 20px 64px" }}>
      <h1>Terms of Use</h1>
      <p style={{ color: "#5b6875" }}>Last updated: 10 July 2026</p>

      <p>
        TapSnap is a free tool that helps you identify a likely spare part for a tap, mixer, valve or
        cartridge from a photo or a few questions. By using TapSnap you agree to these terms.
      </p>

      <h2>TapSnap gives suggestions, not guarantees</h2>
      <p>
        Part matches are <b>best-effort suggestions</b> generated by automated image matching. They can be
        wrong, incomplete, or out of date. A photo can look like several different parts, brands supersede
        and re-tool parts, and sizes matter. <b>Always confirm the exact part</b> against the item in your
        hand — check the size, shape and fit, and cross-check the part number with the manufacturer or
        retailer — before you buy or fit anything.
      </p>

      <h2>No liability</h2>
      <p>
        To the fullest extent permitted by law, TapSnap and its operator are not liable for any loss, cost,
        damage, wasted purchase, water damage, or injury arising from reliance on a match, part number,
        price, availability, or link shown in the app. You use the information at your own risk and remain
        responsible for verifying parts and for any plumbing work. Nothing here excludes rights you have
        under the New Zealand Consumer Guarantees Act or Australian Consumer Law that cannot lawfully be
        excluded.
      </p>

      <h2>Part data</h2>
      <p>
        Part numbers and images are sourced from manufacturer and retailer listings and are provided for
        identification only. Brand names, part numbers and trademarks belong to their respective owners;
        TapSnap is not affiliated with, endorsed by, or sponsored by them.
      </p>

      <h2>Third-party links</h2>
      <p>
        &ldquo;Where to buy&rdquo; and reference links go to third-party websites we don&apos;t control.
        Prices, stock and product details on those sites are theirs, not ours.
      </p>

      <h2>Acceptable use</h2>
      <p>
        Use TapSnap for its intended purpose — identifying spare parts. Don&apos;t attempt to disrupt,
        scrape at scale, or misuse the service.
      </p>

      <h2>Changes</h2>
      <p>We may update these terms; the date above shows the latest version.</p>

      <h2>Contact</h2>
      <p>
        Questions? Email <a href="mailto:myhappyplace@web.de">myhappyplace@web.de</a>. See also our{" "}
        <a href="/privacy">Privacy Policy</a>.
      </p>
    </main>
  );
}
